[build]
  command = "npm run build"
  publish = "dist"
  functions = "server"

[functions]
  node_bundler = "esbuild"

  [functions.node_bundler_esm]
    external_node_modules = ["@replit/vite-plugin-cartographer", "pg-native", "@babel/preset-typescript"]

[context.production]
  functions.external_node_modules = ["@replit/vite-plugin-cartographer", "pg-native", "@babel/preset-typescript"]
